default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: kval
  password: 
  timeout: 5000
  
development:
  <<: *default
  database: dev

production:
  <<: *default
  database: ENV['DATABASE_URL']
